### ISSUE TITLE
Port server to ES modules

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#15]
Currently the server uses Common.js modules. The conversion to TypeScript from #14 should simplify a bit the process to switch to ES modules instead.

Note the following from #13:

> At some point we will move to ESM and TypeScript should make this transition easier, however there are some risks because require is also used dynamically so this might make errors harder to catch. I think some of this was done to bypass circular dependencies between files, not sure if this would be problematic in ESM.

Additional tasks:

- Merge `*_interface.ts` files back into their original files.
- Look for TODOs about circular dependency checks and solve them.
- Update Electron dependencies that would not work due to CJS: `electron-debug`, `electron-dl`.

**Comment by birdmanmandbir** [comment]
Will this cause JS Backend note migration(to ESM)?

**Comment by eliandoran** [comment]
@birdmanmandbir , although I can't say with certainty, I would say that ESM migration should not affect backend scripts.
The reason is that backend scripts do not use `require` as far as I know.

**Comment by eliandoran** [comment]
@meichthys , generally I would say yes, but maybe we should wait a bit more to see how the original TypeScript conversion of the server went.

**Comment by JYC333** [comment]
Related PR merged

**Comment by BeatLink** [comment]
> @birdmanmandbir , although I can't say with certainty, I would say that ESM migration should not affect backend scripts. The reason is that backend scripts do not use `require` as far as I know.

Hi, one of my scripts actually use require to extend the day.js library 

https://github.com/BeatLink/trilium-scripts/blob/main/Agenda/updateAgenda.js
