### ISSUE TITLE
Remove hard-coded `better-sqlite3` binaries

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#229]
In `bin/better-sqlite3` there are `.node` files containing the native dependencies of `better-sqlite3` for every platform.

Theoretically prebuilds should already be available if the right combination of Node.js + Electron is used, without having to deal with `electron-rebuild`.

These `.node` files are used in:

*   `package.json` when doing `qswitch-server` and `qswitch-electron`.
*   In all of the build scripts. It might be worth removing them and see if the builds can handle downloading the right prebuilt on their own.

**Comment by JYC333** [comment]
I'm looking at this one, and find that using `electron-forge` to build package for different platforms is easier only try to remove `.node` files. Is there still a need to keep `zip` or `tar.xz` files in release? Feels like `electron-forge` will create installer for different platforms.

Didn't go deep to explore how to add extra files into `zip` file in `electron-forge`, if we still want to keep binary files (not sure whether I understand correctly about those `tar.xz` and `zip` files) maybe packing with `zip` by `electron-forge` is one option.

**Comment by eliandoran** [comment]
> I'm looking at this one, and find that using electron-forge to build package for different platforms

That is correct. My long-term plan is to remove `electron-packager` and keep `electron-forge` for everything instead. However, the server build (which does not contain electron) still needs to be built separately.

> Is there still a need to keep zip or tar.xz files in release?

I think the original idea was to have portable versions as well, but I'm pretty sure `electron-forge` supports zip packages as well.

**Comment by JYC333** [comment]
PR merged
