### ISSUE TITLE
(Feature request) Add a Windows installer

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#23]
### Describe feature

See https://github.com/zadam/trilium/issues/2081 for more info.

Digital signing to be done separately in #22 .

**Comment by root-hal9000** [comment]
didn't see any mention of it in the original discussion, so I am just making a note of it here for the record: if we are already going the mile to have a windows installer, maybe we should check on what's needed to also have it available for windows package managers (winget)? I am assuming it's not a whole lot more.

**Comment by eliandoran** [comment]
> didn't see any mention of it in the original discussion, so I am just making a note of it here for the record: if we are already going the mile to have a windows installer, maybe we should check on what's needed to also have it available for windows package managers (winget)? I am assuming it's not a whole lot more.

@root-hal9000 , that is a good point indeed. I believe it requires signing (see #22).
I'll create a separate ticket for it.
