### ISSUE TITLE
Frontend JS code exeution error

### ISSUE THREAD

**Issue by Nriver** [TriliumNext/Notes#244]
Hi, is there anything changed in the code exeution. My code for upgrade the theme background in [Bing Daily Theme](https://github.com/Nriver/bing-daily-theme) does not work in the new version. There's an error upon execution:
![1](https://github.com/user-attachments/assets/a50a7750-26f3-463f-9705-f69b62476d71)

```
Execution of JS note "UpdateWallpaper.js" with ID FiL8BgMQ3alL failed with error: Load of script note "UpdateWallpaper.js" (FiL8BgMQ3alL) failed with: server error: Missing start note or origin entity.
```

**Comment by eliandoran** [comment]
@Nriver , it could have been broken due to the TypeScript integration. I will have a look ASAP.

**Comment by eliandoran** [comment]
@Nriver , thank you for your review. It should be OK now.

![image](https://github.com/user-attachments/assets/26b0b324-e5ce-486c-a8e9-236f7c1b31d1)
