### ISSUE TITLE
How to switch servers?

### ISSUE THREAD

**Issue by richardji7** [TriliumNext/Notes#280]
My desktop TriliumNote was pointed at a test server which I did some testing.  Now I want to point at a newly created server.  How do I abandon the old and connect to the new one?  I tried uninstall the app but it apparently didn't get rid of the previous information.  I basically want to delete the desktop data that when I launch it, it will ask me to connect to a new server or setup new again, just like the first time I install it.

**Comment by eliandoran** [comment]
Hi, @richardji7 .

If you have no data that you need to backup you can simply delete the data directory.

On Windows, open Windows Explorer and type %appdata% in the address bar. Look for trilium-data and simply copy and paste it.

On Linux, the data directory is in ~/.local/share/trilium-data.

**Comment by eliandoran** [comment]
You can also change the server you are syncing with by going to the Menu -> Options -> Sync and changing the "Server instance address".

**Comment by richardji7** [comment]
@eliandoran Thanks again.  I did try to change server but it told me that, forgot the exact message, but it can't because it's already sync with one server.  However, nuke the trilium-data directory got me back to the fresh install state.

**Comment by eliandoran** [comment]
@richardji7 , sounds good. I'll close the issue now if it's solved.
