### ISSUE TITLE
(Bug report) 0.90.2-beta cannot sync to trilium 0.63.7 server

### ISSUE THREAD

**Issue by deajan** [TriliumNext/Notes#284]
### TriliumNext Version

0.90.2-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 2022H2 x64

### Description

Hi,

Just gave a test drive to latest TriliumNext beta.
I run as portable eg `TRILIUM_DATA_DIR=c:\mydatapath`

So far so good, I cannot sync it to my Trilium 0.63.7 server.

Hope the logs are useful.

### Error logs

(node:21460) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `trilium --trace-warnings ...` to show where the warning was created)
Generated session secret
DB not initialized, please visit setup page
DB size: 4 KB
{
  "appVersion": "0.90.2-beta",
  "dbVersion": 228,
  "nodeVersion": "v20.15.0",
  "syncVersion": 32,
  "buildDate": "2024-07-28T07:12:19Z",
  "buildRevision": "1d142b9e572bc5558997f0cf33523da3dbfce174",
  "dataDirectory": "c:\\Users\\user\\Documents\\trilium-windows-x64-0.90.2-beta\\trilium-windows-x64\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-07-29T14:33:08.186Z"
}
CPU model: AMD Ryzen 7 1800X Eight-Core Processor         , logical cores: 16 freq: 3593 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Listening on port 37840
Getting document options FROM sync server.
Creating database for sync
Schema and not synced options generated.
Triggering sync.
Slow 200 POST /api/setup/sync-from-server with 20 bytes took 171ms
Sync failed: 'Option 'syncServerHost' doesn't exist', stack: Error: Option 'syncServerHost' doesn't exist
    at Object.getOption (file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/options.ts:23:15)
    at get (file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/sync_options.ts:14:70)
    at Object.isSyncSetup (file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/sync_options.ts:22:32)
    at file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/sync.ts:54:30
    at Object.doExclusively (file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/sync_mutex.ts:13:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.sync (file:///C:/Users/user/Documents/trilium-windows-x64-0.90.2-beta/trilium-windows-x64/resources/src/services/sync.ts:53:16)
Returning sync stats: {"initialized":false,"outstandingPullCount":0}
304 GET /api/sync/stats with 46 bytes took 1ms
Returning sync stats: {"initialized":false,"outstandingPullCount":0}
304 GET /api/sync/stats with 46 bytes took 1ms
Returning sync stats: {"initialized":false,"outstandingPullCount":0}
304 GET /api/sync/stats with 46 bytes took 1ms

**Comment by eliandoran** [comment]
Hi, @deajan .

Thank you for the report, I can reproduce the issue on my side as well. Most likely caused by the update to ESM.

**Comment by eliandoran** [comment]
@deajan , it should be OK now, I would appreciate a re-test on https://github.com/TriliumNext/Notes/actions/runs/10149142971 (once the CI finishes).

**Comment by deajan** [comment]
I've tested said artifact.
So far so good, sync now works.

I've just noted another set of errors as shown below:
```
(node:17812) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `trilium --trace-warnings ...` to show where the warning was created)
Generated session secret
DB not initialized, please visit setup page
DB size: 4 KB
{
  "appVersion": "0.90.2-beta",
  "dbVersion": 228,
  "nodeVersion": "v20.15.0",
  "syncVersion": 32,
  "buildDate": "2024-07-29T17:43:23Z",
  "buildRevision": "99ca701a5c8b91050a58b7dc788f4307c8fc31b1",
  "dataDirectory": "c:\\Users\\User\\Downloads\\trilium-windows-x64\\trilium-b",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-07-30T07:30:10.871Z"
}
CPU model: Intel(R) Xeon(R) E-2286M  CPU @ 2.40GHz, logical cores: 16 freq: 2400 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Listening on port 37840
[17812:0730/093013.015:ERROR:interface_endpoint_client.cc(722)] Message 6 rejected by interface blink.mojom.WidgetHost
[17812:0730/093013.015:ERROR:interface_endpoint_client.cc(722)] Message 7 rejected by interface blink.mojom.WidgetHost
[17812:0730/093013.015:ERROR:interface_endpoint_client.cc(722)] Message 0 rejected by interface blink.mojom.WidgetHost
```

@eliandoran As "everyone" member of the org, I pledge to test all your beta builds if I can. I cannot help you guys with code, but I can with tests and perhaps funding, and of course a Authenticode certificate if needed. Just ping me whenever.

**Comment by eliandoran** [comment]
@deajan , thank you, your testing so far has been really helpful.

Regarding the errors you've found, do they affect the user experience in any way? I suppose they might be related to the Electron build in some way.

**Comment by deajan** [comment]
Nope, no visible errors so far.
