### ISSUE TITLE
Trilium-ckeditor5 Question

### ISSUE THREAD

**Issue by FreedomClannad** [TriliumNext/Notes#286]
Boss, I have a few questions.
1. Is the libraries/ckeditor/ckeditor.js in the Notes library compiled by https://github.com/TriliumNext/trilium-ckeditor5/tree/main/packages/ckeditor5-build-balloon-block?
2. I encountered many problems when installing with yarn. If it is compiled by ckeditor5-build-balloon-block, can you send me the yarn.lock file? Thank you very much.

**Comment by rauenzi** [comment]
1. It should be yes
2. I wouldn't recommend installing with yarn personally and have no yarn.lock file

**Comment by eliandoran** [comment]
@FreedomClannad , here are my notes regarding building the CKeditor:

To set up the repository:

```git
git clone https://github.com/TriliumNext/trilium-ckeditor5.git
cd trilium-ckeditor5.git
yarn install
```

To trigger the build run:

```git
yarn build
```

So yes, yarn is needed for CKEditor build, but npm for the main project.

**Comment by eliandoran** [comment]
Here's the `yarn.zip`.

[yarn.zip](https://github.com/user-attachments/files/16461927/yarn.zip)

Also make sure you are on the latest `main` branch (just merged a version update).

Feel free to reopen the issue if you still need some more info.

**Comment by FreedomClannad** [comment]
Thank you so much
