### ISSUE TITLE
#run=frontendStartup does not work in mobile mode

### ISSUE THREAD

**Issue by olunju** [TriliumNext/Notes#290]
### TriliumNext Version

0.63.7

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 & Google Chrome

### Description

I render a new menu item with JS, but in mobile mode, JS does not execute and the note uses the #run=frontendStartup tag;
How to make it work on mobile? 
Thanks

**Comment by eliandoran** [comment]
@olunju , could you try `#run=mobileStartup` instead of `#run=frontendStartup`?

**Comment by olunju** [comment]
> @olunju , could you try `#run=mobileStartup` instead of `#run=frontendStartup`?

Thank you, it worked. but why not include this option in the attributes tip?

![image](https://github.com/user-attachments/assets/3e24efb7-817c-4296-8df2-1dcd48671c65)

**Comment by eliandoran** [comment]
@olunju , apparently the feature was added three years ago by a third party and they probably just forgotten to update the docs. I've added it in c0a26889e46e7a94c8ab93f357b5c37f2008b5df.

**Comment by olunju** [comment]
Thank you
