### ISSUE TITLE
(Bug report) Tray icon is missing on windows

### ISSUE THREAD

**Issue by JustMrPhoenix** [TriliumNext/Notes#311]
### TriliumNext Version

0.90.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 Pro 23H2

### Description

After updating to TriliumNext the tray icon stopped working. I have tray enabled in settings and I restarted the app multiple times. It was working fine with the [latest Trilium build](https://github.com/zadam/trilium/releases/tag/v0.63.7). I did not see any errors in the console or logs.

**Comment by eliandoran** [comment]
@JustMrPhoenix , thank you for the report. I was not aware of this, it got broke while changing the icons.
If you're interested in testing or the tray is important to you, you can grab the latest development build (should be quite stable). The artifacts will be available here: https://github.com/TriliumNext/Notes/actions/runs/10305812510

If I may ask, how important or useful is the tray icon for you?

**Comment by JustMrPhoenix** [comment]
I've tested the build you linked and it does indeed fix the tray issue, thanks!
As for why I like having the tray icon, I see some benefits:
- Having Trilium start instantly (since it never stopped lol) while clicking it
- Having the local API listener running for web clipper
- Saves the window in the exact state I left it (ie scrolling)
Last two can be done by just minimizing the app but I like my taskbar clear
