### ISSUE TITLE
Update available points to Trilium download instead of TriliumNext

### ISSUE THREAD

**Issue by sblatnick** [TriliumNext/Notes#313]
### TriliumNext Version

0.90.2-beta

### What operating system are you using?

Linux

### What is your setup?

Local (no sync)

### Operating System Version

Debian Testing

### Description

"Version 0.90.3 is available, click to download" points to https://github.com/zadam/trilium/releases/tag/v0.63.7 by mistake.

**Comment by eliandoran** [comment]
@sblatnick , this is a good catch. I think we couldn't catch it earlier since the updater ignores beta releases.

I will have a look and it will be fixed starting with the next version.

**Comment by sblatnick** [comment]
Thanks! Glad to help :-)
