### ISSUE TITLE
Add back Alpine build

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#315]
In #314 we had to use `bullseye-slim` instead of `alpine` due to issues with Node 20 on `armv7` builds.
It would be nice to have Alpine builds, but only for `x86` and `arm64` builds.

**Comment by perfectra1n** [comment]
I can add this back :)

**Comment by eliandoran** [comment]
Done in https://github.com/TriliumNext/Notes/pull/366 .
