### ISSUE TITLE
Markdown Latex support

### ISSUE THREAD

**Issue by Nertonm** [TriliumNext/Notes#32]
### Describe feature

Enhance support for LaTeX notation in Markdown.

**Comment by root-hal9000** [comment]
hey @Nertonm , could you flesh out your ideas about what enhanced support looks like to you? I am not super familiar with LaTeX (it has been on my learning to-do list), so this might be a stupid question - but it might help if you can spell out what you want.
I assume it's unrelated to the ability to just straight up [preview LaTex](https://github.com/rauenzi/Trilium-LaTeXPreview)

**Comment by SiriusXT** [comment]
Trilium supports latex formulas.
