### ISSUE TITLE
(Bug report) Link to releases page is wrong

### ISSUE THREAD

**Issue by Alumniminium** [TriliumNext/Notes#320]
### TriliumNext Version

0.90.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

NA

### Description

https://github.com/TriliumNext/Notes/issues/321 sorry, I don't seem to have permissions to transfer issues so I have to link to it.

**Comment by eliandoran** [comment]
Thank you for bringing it to my attention, @Alumniminium .

I've transferred the issue and replied to it (it was already fixed).
