### ISSUE TITLE
Link to releases page is wrong

### ISSUE THREAD

**Issue by ndaidong** [TriliumNext/Notes#321]
This link goes to Zadam's original repository, not [TriliumNext](https://github.com/TriliumNext/Notes/releases)

![Screenshot from 2024-08-10 08-42-42](https://github.com/user-attachments/assets/4ebe6222-ba47-4b76-b187-59c43dc2b985)

**Comment by eliandoran** [comment]
@ndaidong , thank you for the report. The issue has been reported in #313 and solved. However the fix will only be visible for users of 0.90.4, when a new version will be available.
