### ISSUE TITLE
Upgrade bootstrap dependencies

### ISSUE THREAD

**Issue by JYC333** [TriliumNext/Notes#335]
Bootstrap are recommended to upgrade from v4 to v5

**Comment by eliandoran** [comment]
@JYC333 , I believe every one of these subtasks should be a separate issue, since they imply quite a bit of testing.
We would also have to start adding some integration tests before we update big stuff such as CodeMirror and autocomplete.js.

**Comment by JYC333** [comment]
Closed #381
