### ISSUE TITLE
(Bug report) katex is not defined

### ISSUE THREAD

**Issue by huangweixiao** [TriliumNext/Notes#344]
### TriliumNext Version

0.90.4

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Synology Inc.     docker

### Description

VM29:6 Uncaught (in promise) ReferenceError: katex is not defined
    at <anonymous>:6:1485979
    at <anonymous>:6:1487442
    at <anonymous>:6:1487425
    at zL (<anonymous>:6:1487430)
    at LL (<anonymous>:6:1485963)
    at qL.updateMath (<anonymous>:6:1492573)
    at YL._addFormView (<anonymous>:6:1497489)
    at YL._showUI (<anonymous>:6:1496222)
    at mg.<anonymous> (<anonymous>:6:1501393)
    at mg.fire (<anonymous>:6:470940)

**Comment by huangweixiao** [comment]
我恢复到 到/zadam/trilium 的最后版本 就正常   用到这里版本 切换好几个版本都不行  
"I reverted to the latest version of /zadam/trilium, and everything worked fine. However, when I switched to several other versions, it didn't work."

**Comment by eliandoran** [comment]
@huangweixiao , thank you for the bug report.
We are aware of this issue in https://github.com/TriliumNext/Notes/issues/297 and we are going to try to fix it as soon as possible.
