### ISSUE TITLE
'A JavaScript error occurred in the main process' when launching Trilium

### ISSUE THREAD

**Issue by maphew** [TriliumNext/Notes#368]
### TriliumNext Version

0.090.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

win 11 pro (10.0.22631 N/A Build 22631)

### Description

I haven't used this laptop in 3 weeks. Tonight I get an error when trying to launch Trilium. I've upgraded to latest beta release, same err. 

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> Error: getaddrinfo ENOTFOUND http://100.82.119.2:8080/
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
>     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
> 

After pressing OK on the error dialog a completely blank window opens. There are not decorators or window controls of any kind.

The ip address listed in the error is to the NAS on my Tailscale network, which is running. Ping to that address works. Visting the address with browser prompts for Trilium password. 

_update:_ after logging in with the password, Trilium-in-browser works as usual. There is a notification that a new version is available (0.63.7). Current version is 0.63.5.

### Error logs

* Today: [trilium-2024-08-24.log](https://github.com/user-attachments/files/16739067/trilium-2024-08-24.log)
* Previous  session: [trilium-2024-08-03.log](https://github.com/user-attachments/files/16739068/trilium-2024-08-03.log)

**Comment by eliandoran** [comment]
@maphew , this does appear to be a bug on our side.

From what I see the underlying request to the sync server fails, but nevertheless this should not crash the application.

If possible I'd appreciate opening up the `document.db` in `C:\Users\maphe\AppData\Roaming\trilium-data` using your favorite SQLite editor (DB Browser for SQLite should work well) and go to the `options` table and look for `syncServerHost`.

On my side I have a functional sync but with `https`, maybe something wrong with the `http` protocol.

**Comment by maphew** [comment]
interesting, `syncServerHost: http://nas:8080` in document.db.

with Tailscale running:
```
>nslookup nas
Server:  console.gl-inet.com
Address:  192.168.8.1

Name:    nas.lan
Address:  192.168.8.134

> ping nas

Pinging nas.tailc5be0.ts.net. [100.82.119.2] with 32 bytes of data:
Reply from 100.82.119.2: bytes=32 time=35ms TTL=64
...etc
```

Shutting down tailscale, nslookup stays the same, while ping switches to 192.168.8.134.
Running Trilium now from the same shell shows the same error dialog originally reported, with the 100.* ip address instead of 192, however the shell console reports the hostname address. I was certain at one point trilium-shell used 192 also, but in repeat experiments it's showing the hostname, as below.

```
A:\apps\trilium-windows-x64>ping nas

Pinging nas.lan [192.168.8.134] with 32 bytes of data:
Reply from 192.168.8.134: bytes=32 time=5ms TTL=64
...snip...

A:\apps\trilium-windows-x64>trilium.exe

(node:3588) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `trilium --trace-warnings ...` to show where the warning was created)
DB size: 122703 KB
Becca (note cache) load took 42ms
{
  "appVersion": "0.90.4",
  "dbVersion": 228,
  "nodeVersion": "v20.15.0",
  "syncVersion": 32,
  "buildDate": "2024-08-09T22:05:59Z",
  "buildRevision": "2a5c444eff3eb99389339716ea8bfc989be90ecd",
  "dataDirectory": "C:\\Users\\maphe\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-08-26T03:27:08.214Z"
}
CPU model: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     , logical cores: 16 freq: 3793 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Table counts: notes: 1130, revisions: 41, attachments: 132, branches: 1145, attributes: 2030, etapi_tokens: 2, blobs: 816
Slow query took 20ms: SELECT id, entityId FROM entity_changes LEFT JOIN notes ON entityId = notes.noteId WHERE entity_changes.isErased = 0 AND entity_changes.entityName = 'notes' AND notes.noteId IS NULL
Slow query took 51ms: SELECT notes.noteId, notes.type, notes.mime FROM notes JOIN blobs USING (blobId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
All consistency checks passed with no errors detected (took 118ms)
Sync failed: 'Request to GET http://nas:8080/api/setup/status failed, error: net module can only be used after app is ready', stack: Error: Request to GET http://nas:8080/api/setup/status failed, error: net module can only be used after app is ready
    at generateError (file:///A:/apps/trilium-windows-x64/resources/src/services/request.ts:230:12)
    at file:///A:/apps/trilium-windows-x64/resources/src/services/request.ts:135:20
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processTimers (node:internal/timers:511:9)
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
(node:3588) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_CONNECTION_REFUSED
```
![image](https://github.com/user-attachments/assets/cf564556-78f9-4658-a9c6-8816e317f409)

**Comment by maphew** [comment]
I edited `document.db` and changed _syncServerHost_ to be the 192 ip address and port. The popup err continues to use the 100 ip instead. I also flipped between http and https - no change. 

(https in a browser refuses to connect: _An error occurred during a connection to 192.168.8.134:8080. SSL received a record that exceeded the maximum permissible length._)

**Comment by eliandoran** [comment]
@maphew , your problem is most likely the DNS cache that comes with Electron.

Can you try to clear your system DNS cache via `ipconfig /flushdns`
I don't know where Electron's DNS cache is, unfortunately. Maybe you can try to rename the `%appdata%\TriliumNext Notes` directory to something else and run again the application.

The application should not crash if it cannot find the sync but I can't see to reproduce it on my side even if I put in a fake host. Do you have any out of the ordinary DNS resolver in your network?

**Comment by maphew** [comment]
Interesting. I upgraded my trilium server to zadam's latest, and added some pages using the browser interface and importing a zip of html pages. Now on my laptop starting Trilium has the same error as in original post, but the console is full of hash check and sync messages. --> so communication with the server is working Just Fine.

```
(node:22452) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `trilium --trace-warnings ...` to show where the warning was created)
DB size: 122703 KB
Becca (note cache) load took 20ms
{
  "appVersion": "0.90.4",
  "dbVersion": 228,
  "nodeVersion": "v20.15.0",
  "syncVersion": 32,
  "buildDate": "2024-08-09T22:05:59Z",
  "buildRevision": "2a5c444eff3eb99389339716ea8bfc989be90ecd",
  "dataDirectory": "C:\\Users\\maphe\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-08-28T13:39:03.439Z"
}
CPU model: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     , logical cores: 16 freq: 3793 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
Table counts: notes: 1130, revisions: 41, attachments: 132, branches: 1145, attributes: 2030, etapi_tokens: 2, blobs: 816
All consistency checks passed with no errors detected (took 33ms)
(node:22452) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_CONNECTION_REFUSED
Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":31911}
Sync jfA795rI2X: Pushing 76 sync changes in 490ms
Nothing to push
Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":31991}
updated: {notes: [21goB4HvTuFu, 27018iHbYU0l, 277Z0OnJsrtd, ...
...
Sync giWQoTUINf: Pulled 52 changes in 1377 KB, starting at entityChangeId=7505 in 166ms and applied them in 41ms, 0 outstanding pulls
Finished pull
Nothing to push
Content hash computation took 15ms
Content hash checks PASSED
Sending message to all clients: {"type":"sync-finished","lastSyncedPush":35052}
Nothing to push
Finished pull
Nothing to push
Content hash computation took 22ms
Content hash checks PASSED
Sending message to all clients: {"type":"sync-finished","lastSyncedPush":35052}
```
_following up on your other suggestions next_

**Comment by maphew** [comment]
syncProxy in document.db and host in options.ini are both empty or commented out.

**Comment by maphew** [comment]
I get the same error and white screen using latest Zadam Trilium (which I now think of as _zilium_, a name with some attraction). So it looks like there's something screwey with my appdata folder. I'll try move it out of the way and start as if a new computer and see what happens.

**Comment by maphew** [comment]
`ipconfig /flushdns` did not change anything. 
I don't have time for any more testing today. More tonight/tomorrow.

**Comment by maphew** [comment]
**I removed all 3 trilium folders in `%appdata%`: same error.**
While the error message is open, `pslist trilium` shows 2 processes running.
After dismissing the error and the white screen is showing, this time with a title bar saying "TriliumNext Notes Setup", there are 4 trilium processes.

I've tried forcing Electron/Chromium to reload by using `ctrl-R` and `ctrl-shift-R` while white window is open ([ref](https://stackoverflow.com/questions/51227765/electronjs-caching-issue)) --> just repeats the connection refused error in console, `(node:8092) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_CONNECTION_REFUSED`. Similarly there's no useful information revealed in chromium developer console, `ctrl-shift-I` (ref).

Oh! same symptoms reported for zilium in 2023, https://github.com/zadam/trilium/issues/3869.
 
For one person issue resolved itself by launching with `--trace-warnings` flag. --> doesn't change anything for me.
For another, on arch linux, it resolved itself after a full system upgrade. I ran Windows Update which installed a cumulative update with required reboot. Again, no change for me.

```
PS A:\apps\trilium-windows-x64> .\trilium.exe --trace-warnings
PS A:\apps\trilium-windows-x64>
(node:7956) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
    at emitExperimentalWarning (node:internal/util:264:11)
    at ModuleLoader.jsonStrategy (node:internal/modules/esm/translators:463:3)
    at callTranslator (node:internal/modules/esm/loader:272:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
DB not initialized, please visit setup page
DB size: 4 KB
{
  "appVersion": "0.90.4",
  "dbVersion": 228,
  "nodeVersion": "v20.15.0",
  "syncVersion": 32,
  "buildDate": "2024-08-09T22:05:59Z",
  "buildRevision": "2a5c444eff3eb99389339716ea8bfc989be90ecd",
  "dataDirectory": "C:\\Users\\maphe\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-08-29T13:44:52.969Z"
}
CPU model: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     , logical cores: 16 freq: 3793 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
(node:7956) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_CONNECTION_REFUSED
```

**Comment by maphew** [comment]
This is curious, the popup error says `getaddrinfo ENOTFOUND http://100.82.119.2:8080/`, however if I ensure that

* tailscale is running, and 
* that ip points to my nas running Trilium server, and 
* that pointing a browser to `http://100.82.119.2:8080/` works, shows a Trilium login prompt or Trilium Notes in browser

I **still** get the popup err.

**Comment by eliandoran** [comment]
@maphew , can you also try renaming %appdata%\TriliumNext Notes to something else?

I ran out of ideas, maybe we can have a meeting in the weekend if we manage to align on the timezone (GMT+03:00).

**Comment by perfectra1n** [comment]
Yeah this one is certainly very interesting, it looks like it's still trying to resolve the IP address (as if it was a hostname). I see [this](https://stackoverflow.com/questions/20724122/i-get-enotfound-node-js-with-ip-address) on StackOverflow, but I see that @maphew is putting in `http://nas:8080` and not an IP. It's strange that Electron is still trying to resolve an IP, however.

**Comment by perfectra1n** [comment]
Perhaps even a quick arrow diagram of the setup, of what networks contain what components for your Trilium setup would help :)

**Comment by maphew** [comment]
> @maphew , can you also try renaming %appdata%\TriliumNext Notes to something else?

I renamed/moved all 3 trilium folders in %appdata%: no change. (`trilium-data`, `Trilium Notes`, `TriliumNext Notes`)
https://github.com/TriliumNext/Notes/issues/368#issuecomment-2317707598

> I ran out of ideas, maybe we can have a meeting in the weekend if we manage to align on the timezone (GMT+03:00).

Wonderful offer, thank you! but it's a long weekend here (Yukon Territory) and we'll be out camping.

> what sync server are you running

Meaning what Trilium server? It's on a Synology NAS. I haven't figured out how to get to the compose file. The image is `zadam/trilium:latest` though.

From browser pointed at the server instance (http://nas:8080/) I get:

> About Trilium Notes
> Homepage: 	https://github.com/zadam/trilium
> App version: 	0.63.7
> DB version: 	228
> Sync version: 	32
> Build date: 	2024-05-30T06:59:06+02:00
> Build revision: 	[95d46b7ce7e0036eeb72b43e1815cc5c00dc214c](https://github.com/zadam/trilium/commit/95d46b7ce7e0036eeb72b43e1815cc5c00dc214c)
> Data directory: 	/home/node/trilium-data

> Also, are you using a reverse proxy, or just Tailscale?

Don't really know what a reverse proxy is, so no?
Tailscale is running on the NAS and my laptop. Turning tailscale off on laptop makes no difference. I haven't tried turning off the NAD one. Will test that.

Home network:

* Nwtel cable modem -->
 * GL Inet router GL-AX1800 --> wifi --> laptop
 * GL Inet router GL-AX1800 --> wired LAN  --> NAS
 * laptop --> wifi <-- NAS

**Comment by maphew** [comment]
**SOLVED**, wound self inflicted :-/  Delete TRILIUM_HOST var and everything works _Just Fine &trade;_

I'm working on python scripts to export/import note trees on 3 different machines in different networks. Access to the sync host trilium server is different from each - it has a diffrent hostname & IP in each. The scripts consult the environment for `TRILIUM_HOST`, a variable I thought I made up. Not so!

Obscuring the issue for me is that (apparently) Trilium uses the host var to communicate with a _local_ backend server, **not** the sync host. This finally came to light by omitting the port number from the var. With `TRILIUM_HOST='100.82.119.2'` instead of `TRILIUM_HOST='http://100.82.119.2:8080/'`the error dialog reports failure on port `37840`!

![image](https://github.com/user-attachments/assets/cf97803b-9c54-40ab-a68e-d27a32b9615c)

Leaving the issue open for the moment since even though this circumstance is technically outside of Trilium's jurisdiction it's an opportunity to document the hazard, and possibly tune the error message to say it's the local backend that's not found instead of the sync server.

**Comment by perfectra1n** [comment]
@TriliumNext/documentation, might be a great spot to highlight :)

**Comment by perfectra1n** [comment]
Glad to hear it's worked out though @maphew, I agree that the environment variables can be a little confusing. I can definitely help flesh out the documentation as well to mention the nuances.

So my understanding, is that once you had cleared out the `TRILIUM_HOST` environment variable, everything worked? Would you mind sharing your full compose / deployment?

**Comment by maphew** [comment]
Yes, removing `TRILIUM_HOST` environment variable got Trilium, both original and Next, working on this machine again.

I don't know to answer the full deployment and compose details question better than I have already. Oh right, I hid that comment above! The sync host is on a Synology NAS, using `zadam/Trilium:latest` image, and I don't know how to get at the compose.yml file.
