### ISSUE TITLE
(Bug report) crash in Chrome 128

### ISSUE THREAD

**Issue by Nriver** [TriliumNext/Notes#386]
### TriliumNext Version

Source code

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

manjaro

### Description

The initialization and login pages work fine, but the page crashes immediately after logging in. The issue persists on Chrome version 128.0.6613.113, including in Incognito mode.

### Error logs

Nothing from browser console.

This is the server log:
```
Generated CSRF token 1l3FBQig-azvHPB_QWdWM3oWFQ-hl2-2OKKk with secret undefined
websocket client connected
```

**Comment by eliandoran** [comment]
@JYC333 also has the same issue. Initially thought it might be related to the hardware acceleration but it does not appear to be the case. 

Either way, it's going to be quite a challenge to debug a crashing browser. 

@Nriver , does the browser crash if you run the latest server binary from develop or only when using the development server using npm run start?

**Comment by Nriver** [comment]
I pull the latest code from develop branch and run it with `npm run start-server`.

**Comment by Nriver** [comment]
Just got an update for 128.0.6613.137, it works fine now : )
