### ISSUE TITLE
(Bug report) Searching with orderBy doesn't work with dated attributes

### ISSUE THREAD

**Issue by brianvanderburg2** [TriliumNext/Notes#441]
### TriliumNext Version

0.90.5-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Debian

### Description

Search string in a search note is "#bill orderBy #due".  #due labels are set on notes in the form YYYY-MM-DD, however it only seems to sort based on the YYYY portion

**Comment by brianvanderburg2** [comment]
This appears to be caused by **src/services/search/expressions/order_by_and_limit.ts**.  The function **isNumber** reports that a string of form "####-##-##" is a number since **parseInt** will parse it down to just the year, then **parseFloat** used in **execute** does the same and strips it down to just the year.  The ordering works, but only based on the year and not the entire date string.

**Comment by eliandoran** [comment]
@brianvanderburg2 , wonderful analysis, I'll have a look.

**Comment by eliandoran** [comment]
@brianvanderburg2 ,

Should be solved by https://github.com/TriliumNext/Notes/pull/451.
