### ISSUE TITLE
(Feature request) Resizing Left Panel/TOC is too difficult

### ISSUE THREAD

**Issue by eeshaa1** [TriliumNext/Notes#443]
### Describe feature

Please add a setting or something to increase the "zone" your mouse needs to be near the edge of the left panel/TOC to be able to resize them.

**Comment by SiriusXT** [comment]
The default edge area has 5px for resizing, if you still feel the gap is too small you can increase the gap by adding the following css.

```
.gutter.gutter-horizontal{
    width: 20px !important;
}
```
See: https://github.com/TriliumNext/Docs/blob/main/Wiki/themes.md#custom-css

**Comment by eliandoran** [comment]
Closing as this can be handled with custom CSS as mentioned with @SiriusXT . We need to keep the code base as lean as possible, so we will not add a custom option for this.
