### ISSUE TITLE
(Bug report) mindmap note suddenly show with file note

### ISSUE THREAD

**Issue by clssw1004** [TriliumNext/Notes#467]
### TriliumNext Version

0.90.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 23H2 22631.4249

### Description

I create a note with type mindmap，after i add some nodes in this note，it's suddenly changes to a file type note,shows some json string with mindmap source；
I can‘t reproducing this,I'm be sure not use [advance->convert to attachment] menu do this

**Comment by eliandoran** [comment]
@clssw1004 , I have had one more report of this issue although I'm not sure what triggers it. 

Could you please send me a .zip export of the note that happened to have this issue? Of course, provided it contains no confidential or personally identifiable information.

**Comment by clssw1004** [comment]
> @clssw1004 , I have had one more report of this issue although I'm not sure what triggers it.
> 
> Could you please send me a .zip export of the note that happened to have this issue? Of course, provided it contains no confidential or personally identifiable information.
I try to export the note after this happened,but it's expoort a empty file(0kb) with name xx.undefined

**Comment by eliandoran** [comment]
@clssw1004 , what server version do you have? Is it same version as the desktop application, or an older version?

**Comment by eliandoran** [comment]
@clssw1004 , I've completed the analysis (seen above). Let me know if this fixes the issue for you.
