### ISSUE TITLE
(Feature request) Introduce stable tag on docker hub

### ISSUE THREAD

**Issue by tom-keim** [TriliumNext/Notes#488]
### Describe feature

According to your documentation it is not recommended to use the latest tag for docker installations, as that can contain unstable minor versions.

I am using watchtower as a way to automatically update all docker containers, this will not work when using specific version tags.

Can a stable tag be introduced, which will always contain the latest stable version?

**Comment by eliandoran** [comment]
@perfectra1n , willing to have a look at this?

**Comment by perfectra1n** [comment]
Sure! My immediate response is that Watchtower is a world of pain, and I suggest using Renovate instead (as you can merge PRs and revert if/when needed). But I can definitely look into adding a `stable` tag upon a new release being done.

**Comment by tom-keim** [comment]
That's great! I understand your point about Watchtower, but I like the hands-off updates, and with frequent backups it's good enough for me.
