### ISSUE TITLE
Bring back unit and integration tests

### ISSUE THREAD

**Issue by eliandoran** [TriliumNext/Notes#49]
There are a few unit and integration tests for the server in `spec` and `spec-es6`.

The goal is to convert these tests to TypeScript and adapt them for modern use.

**Comment by alexpietsch** [comment]
@eliandoran I don't know if you already stared with this, but I had some time and could enable the jasmine tests to be executed. Two tests still fail.
I pushed my changes to [this branch](https://github.com/TriliumNext/Notes/tree/feat/ts-unit-and-integration-tests) if you want to continue with that.

**Comment by eliandoran** [comment]
@alexpietsch , feel free to open a PR since I haven't started yet.
