### ISSUE TITLE
(Feature request) Add Options Launcher 

### ISSUE THREAD

**Issue by meichthys** [TriliumNext/Notes#619]
### Describe feature

As discussed in #618 we could improve the access to options by allowing options to be configured as a sidebar launcher item.

**Comment by adoriandoran** [comment]
I was thinking the same, actually. It would be nice if it will come pinned by default on the toolbar above the 'Hide panel' icon.

![image](https://github.com/user-attachments/assets/42331f41-3442-4104-ae93-e3ba01914e8d)
