### ISSUE TITLE
(Bug report) after `Open New Window`, external links are opened in pop-up instead of default browser

### ISSUE THREAD

**Issue by dogfuntom** [TriliumNext/Notes#660]
### TriliumNext Version

0.90.8

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro 22H2

### Description

1. `Open New Window`
2. double-click or otherwise open an external link
3. a small pop-up window is opened

However, if you switch back to the first window and open the very same note and then open the very same link in it – the link goes into the default browser (Firefox in my case).

**Comment by dogfuntom** [comment]
After a quick and shallow debug attempt I noticed that in both cases the execution ends up at:
https://github.com/TriliumNext/Notes/blob/21f8a297619654f3eee18f8b0f631f3789694bb6/src/public/app/services/link.js#L254
So the cause of this difference is not there it seems.

**Comment by eliandoran** [comment]
@dogfuntom , I believe this was already fixed as part of #559 .
You should be able to test it in the v0.90.11-beta release, if you wish.
New stable coming soon.

**Comment by dogfuntom** [comment]
Indeed, I tried the https://github.com/TriliumNext/Notes/releases/tag/v0.90.11-beta and can confirm that the pop-up is gone. Thank you.
