### ISSUE TITLE
Menu positioning problem for KDE Breeze theme

### ISSUE THREAD

**Issue by ea-r1** [TriliumNext/Notes#674]
### Description

When using [KDE Breeze theme](https://github.com/eliandoran/breeze-trilium):
Menu is incorrectly positioned, too far to right side, clipping its content area 

![image](https://github.com/user-attachments/assets/75df1985-ee53-431e-a1dc-f11dc976293e)

v0.90.3 is not affected

Also reported in Breeze-Trilium repository:
[https://github.com/eliandoran/breeze-trilium/issues/15](https://github.com/eliandoran/breeze-trilium/issues/15)

### TriliumNext Version

0.90.12

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

**Comment by ea-r1** [comment]
Quick fix: Open dev console: Ctrl+Shift+I and paste this code:

`$('<style>  ul.dropdown-menu.dropdown-menu-right.show { transform: translate(-'+($('ul.dropdown-menu.dropdown-menu-right').width()+3)+'px, 0px) !important; } </style>').appendTo('html > head')`

**Comment by eliandoran** [comment]
Closing it in favor of https://github.com/eliandoran/breeze-trilium/issues/15, since it's an issue with the theme.
