### ISSUE TITLE
(Bug report) Greek characters with tonos  are not represented correctly

### ISSUE THREAD

**Issue by MateuSai** [TriliumNext/Notes#697]
### Description

ί, GREEK SMALL LETTER IOTA WITH TONOS (https://en.wiktionary.org/wiki/%CE%AF), is seen like this inside Trilium:

![image](https://github.com/user-attachments/assets/0158e552-525f-48c0-b02c-d2d8aca86e37)

The same happens with other characters that also have tonos like ή (https://en.wiktionary.org/wiki/%CE%AE)

To reproduce just paste the character on any note.

### TriliumNext Version

0.90.12

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1715181801~22.04~aba43ee SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux

**Comment by eliandoran** [comment]
@MateuSai , for me these seem to render fine. Did you type the characters manually? It could be that combining diacritical marks are at fault. If so, please provide me a note to import and I'll have a look.

![image](https://github.com/user-attachments/assets/7d6daa2e-459d-4f27-b78a-f2ca1df44d1a)

**Comment by MateuSai** [comment]
Thanks for the quick reply. I tried to paste the character to various apps. The majority represent the character fine, the only ones that represent it wrong that I found are Trilium and VSCodium. So maybe the problem is with javascript apps?

I don't know. Maybe the problem only happens on Linux? Are you using Linux? If you are using Linux and it works for you, I guess the problem is with my system and not with the app, so feel free to close the issue.

**Comment by MateuSai** [comment]
I tried on a Fedora distribution and it works fine. Maybe the problem is with the font then? Does trilium use the default font of the system and I have possible that font don't has the characters in question?

**Comment by eliandoran** [comment]
@MateuSai , if you're using the default theme and have "Override theme fonts" unchecked, then it's going to use the default font of the theme, which is Montserrat and is embedded in the application.

![image](https://github.com/user-attachments/assets/a2334cda-3d78-4adf-9f92-3fd82a692372)

You can double check which font is being used using the inspect element tool:

1. Right click any text -> Inspect
2. In the right side bar, select "Computed".
3. Look for `font-family`.

![image](https://github.com/user-attachments/assets/e2cf5f6f-aefb-4181-b28c-35b76717854d)

I will close the issue as resolved now, but let me know if you are still encountering issues.
