### ISSUE TITLE
(Feature request) Is that possible that enabling to wrap the text in code block?

### ISSUE THREAD

**Issue by m1xds** [TriliumNext/Notes#710]
### Describe feature

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/dc3a4a76-1051-4d43-8a68-7afd8ca8e3c9">
As we can see from the pic, when texts in code block-those perharps are not codes,just because I like the way code block displays-you can't wrap those texts.

**Comment by eliandoran** [comment]
Hi, @m1xds 

You can enable word wrapping for code blocks by going to Options -> Appearance and looking for the "Code Syntax Highlighting for Text Notes" section. There is a checkbox there called "Word wrapping" that should suit you.

Let me know if you have any issues.
