### ISSUE TITLE
(Bug report) Librarys in Excalidraw are broken

### ISSUE THREAD

**Issue by CobriMediaJulien** [TriliumNext/Notes#772]
### Description

In the file canvas.js the following part of the code is broken:

''' 
Promise.all(
            (await note.getAttachmentsByRole('canvasLibraryItem'))
                .map(attachment => attachment.getBlob())
        ).then(blobs => {
            if (note.noteId !== this.currentNoteId) {
                // current note changed in the course of the async operation
                return;
            }
'''

![image](https://github.com/user-attachments/assets/5bf8a158-b302-400d-9ec1-350f17a05c59)

the code return empty blob content.

### TriliumNext Version

0.90.12

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 10

**Comment by CobriMediaJulien** [comment]
For reference:

Zadam integrated libraries allrdy:

https://github.com/zadam/trilium/commit/f37dc6607407ed087baf8b662171863581c7d288

But the feature doesn´t work anymore with triliumnext. I´m also happy for more advice where to search. Maybe i can debug myself with some help.

**Comment by CobriMediaJulien** [comment]
Just an idea:

instead of saving the library in the attachments, how about a own hidden notebook structure and the user can just add the json content there. so the user could manage his library. So this could be rather a feature improvement instead bug fixing.

**Comment by CobriMediaJulien** [comment]
Documentation for fix, until I handle my code better. It's chaos right now:

change in sattachments.ts:
'''
  hasStringContent() {
        const isString = utils.isStringNote(undefined, this.mime);
        console.log(`hasStringContent in sattachment called for MIME: ${this.mime}, Result: ${isString}`);
        return isString;
    }
 ''' 
  undefined was null before.

and in ultis.ts:

'''
function isStringNote(type: string | undefined, mime: string): boolean { ..]
'''

null was replaced with undefined too. then it works like in zadams integration

**Comment by eliandoran** [comment]
Reopening until the PR is merged.

**Comment by eliandoran** [comment]
Done in #787 .
