### ISSUE TITLE
(Bug report) UX: 0.91.1-beta Light-Dark mode under Close Window control

### ISSUE THREAD

**Issue by maphew** [TriliumNext/Notes#778]
### Description

On Win11 the desktop 0.91.1-beta controls for Light & Dark mode are shifted right under the [X] close window control

![image](https://github.com/user-attachments/assets/7d30c288-e930-484a-85af-7145101adb91)

### TriliumNext Version

0.91.1-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 10.0.26100 N/A Build 26100

**Comment by eliandoran** [comment]
@maphew , what are the light & dark mode buttons, where do they come from? I don't think we have this by default, maybe a plugin on your side?

**Comment by maphew** [comment]
umm, they've always been there I think? I haven't gotten to the point of trying to customize theme yet. I just experimented with changing through all the builtin themes and it's the same with all of them. It is possible I don't remember adding something when I was first trying Trilium out though. Where would I look? Searching for 'plugin' and 'dark' doesn't return anything.

![image](https://github.com/user-attachments/assets/852205e5-f5d2-4836-885e-1a1aaacf2c3b)

**Comment by maphew** [comment]
aha, found it, and it is something I added and forgot about: _Theme switch widget for Trilium Notes (https://github.com/zadam/trilium), (c) Matko Dodig 2024_.

My uncertainty points to something that maybe could be provided in the default opening DB: a branch within Options for user added customizations. (Could be somewhere outside of Options too, but within the hidden tree.)
