### ISSUE TITLE
i18n: "Duplicate Subtree" prefix should be translatable

### ISSUE THREAD

**Issue by pano9000** [TriliumNext/Notes#825]
### Description

Hi,

when using the "Duplicate subtree" function, the newly created note will have "(dup)" added as hardcoded suffix to the current note.
This should be translatable as well and the translation string should use some positional parameter, to also allow for RTL languages to correctly translate

Happens in the `duplicateSubtree` function in `src/services/notes.ts` 

### TriliumNext Version

git

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

git

**Comment by pano9000** [comment]
@eliandoran you mentioned that I could assign myself to issues here:
https://github.com/TriliumNext/Notes/issues/820#issuecomment-2557409339

I don't think I have the rights to do that though, as I cannot seem any option for it at the moment

**Comment by eliandoran** [comment]
@pano9000 , you should be able to assign them now. And also create branches directly on our repo.
